"""Block disposable/temp-mail domains at signup."""
from pathlib import Path

# Curated list of well-known disposable domains (from disposable-email-domains)
_DEFAULT_DOMAINS: frozenset[str] = frozenset({
    "0-mail.com", "0815.ru", "10minutemail.com", "10minutemail.net",
    "10minutemail.org", "123-m.com", "126.com", "139.com", "150ml.com",
    "163.com", "1chuan.com", "1pad.de", "20mail.eu", "20minutemail.com",
    "21cn.com", "2fdgdfgdfgdf.tk", "30minutemail.com", "33mail.com",
    "3d-painting.com", "4warding.com", "4warding.net", "4warding.org",
    "60minutemail.com", "675hosting.com", "675hosting.net", "6url.com",
    "75hosting.com", "7tags.com", "9ox.net", "a-bc.net", "agedmail.com",
    "ajaxapp.net", "amail4.me", "anonbox.net", "anonmails.de",
    "anonymbox.com", "antichef.com", "antichef.net", "antichef.org",
    "antispam.de", "baxomale.ht.cx", "beefmilk.com", "binkmail.com",
    "bio-muesli.net", "bobmail.info", "boun.cr", "bouncr.com",
    "boxformail.in", "brennendesreich.de", "buffemail.com", "bugmenot.com",
    "bumpymail.com", "bund.us", "bundes-li.ga", "burnthespam.info",
    "burstmail.info", "buyusedlibrarybooks.org", "byebyemail.com",
    "byom.de", "card.zp.ua", "casualdx.com", "cek.pm", "cellurl.com",
    "centermail.com", "centermail.net", "chammy.info", "childsavetrust.org",
    "chogmail.com", "choicemail1.com", "chong-mail.com", "chong-mail.net",
    "chong-mail.org", "clixser.com", "cmail.club", "cmail.com", "cmail.net",
    "cmail.org", "coldemail.info", "consumerriot.com", "coolandwacky.us",
    "correo.blogos.net", "cosmorph.com", "courriel.fr.nf", "courrieltemporaire.com",
    "crapmail.org", "crazymailing.com", "curryworld.de", "cust.in",
    "cuvox.de", "d3p.dk", "dacoolest.com", "dandikmail.com", "dayrep.com",
    "dbunker.com", "dcemail.com", "deadaddress.com", "deadspam.com",
    "delikkt.de", "despam.it", "despammed.com", "dev-null.cf", "dev-null.ga",
    "dev-null.gq", "dev-null.ml", "devnullmail.com", "dfgh.net", "digdig.org",
    "digital-message.com", "digitalmail.info", "discard.cf", "discard.email",
    "discard.ga", "discard.gq", "discard.ml", "discard.tk", "discardmail.com",
    "discardmail.de", "disposable.com", "disposableaddress.com",
    "disposableemailaddresses.com", "disposableinbox.com", "disposablemails.com",
    "dispose.it", "disposeamail.com", "disposemail.com", "dispostable.com",
    "divermail.com", "dmarc.ro", "dodgeit.com", "dodgit.com", "dodgit.org",
    "doiea.com", "domozmail.com", "donemail.ru", "dontreg.com",
    "dontsendmespam.de", "doquier.tk", "dotmsg.com", "drdrb.com", "drdrb.net",
    "droolingfanboy.de", "dropcake.de", "dropjar.com", "droplar.com",
    "dropmail.me", "duam.net", "dudmail.com", "dumpandjunk.com",
    "dumpmail.de", "dumpyemail.com", "duskmail.com", "e-mail.com",
    "e-mail.org", "e4ward.com", "easy-trash-mail.com", "easytrashmail.com",
    "einmalmail.de", "einrot.com", "einrot.de", "eintagsmail.de",
    "email-fake.cf", "email-fake.com", "email-fake.ga", "email-fake.gq",
    "email-fake.ml", "email-fake.tk", "email60.com", "emailage.cf",
    "emailage.ga", "emailage.gq", "emailage.ml", "emailage.tk",
    "emailfake.com", "emailfake.ml", "emailgo.de", "emailias.com",
    "emailigo.de", "emailondeck.com", "emailspam.cf", "emailspam.ga",
    "emailspam.gq", "emailspam.ml", "emailspam.tk", "emailtemporar.ro",
    "emailtemporario.com.br", "emailtmp.com", "emailto.de", "emailwarden.com",
    "emailz.cf", "emailz.ga", "emailz.gq", "emailz.ml", "emeil.in", "emeil.ir",
    "emkei.cf", "emkei.ga", "emkei.gq", "emkei.ml", "emkei.tk",
    "emz.net", "enterto.com", "ephemail.net", "ephemeral.email",
    "ero-tube.org", "evopo.com", "explodemail.com", "express.net.ua",
    "eyepaste.com", "fake-box.com", "fake-email.pp.ua", "fake-mail.cf",
    "fake-mail.ga", "fake-mail.ml", "fakeinbox.cf", "fakeinbox.com",
    "fakeinbox.ga", "fakeinbox.info", "fakeinbox.ml", "fakeinbox.tk",
    "fakemail.fr", "fakemail.io", "fakemail.net", "fakemailgenerator.com",
    "fammix.com", "fansworldwide.de", "fastacura.com", "fastchevy.com",
    "fastchrysler.com", "fastkawasaki.com", "fastmazda.com", "fastmitsubishi.com",
    "fastnissan.com", "fastsearcher.com", "fastsubaru.com", "fastsuzuki.com",
    "fasttoyota.com", "fastyamaha.com", "fightallspam.com", "filzmail.com",
    "fivemail.de", "fivermail.com", "fixmail.tk", "fizmail.com",
    "flashbox.5july.org", "fleckens.hu", "flemail.ru", "flurred.com",
    "flyspam.com", "forgetmail.com", "fornow.eu", "forspam.net",
    "foxja.com", "fr33mail.info", "fragolina2.tk", "frapmail.com",
    "free-email.cf", "free-email.ga", "free-temp.net", "freebabysittercam.com",
    "freeblackbootytube.com", "freecat.net", "freedompop.us",
    "freefattymovies.com", "freehotmail.net", "freeinbox.email",
    "freemails.cf", "freemails.ga", "freemails.ml", "freemeil.ga",
    "freemeil.gq", "freemeil.ml", "freeplumpervideos.com",
    "freeschoolgirlvids.com", "freesistercam.com", "freeteenbums.com",
    "friendlymail.co.uk", "front14.org", "fuckingduh.com", "fudgerub.com",
    "fuhoy.com", "fukaru.com", "funneledmail.com", "funnymail.de",
    "fuwamofu.com", "fxnxs.com", "fyii.de", "g14l71lb.com", "gafy.net",
    "gamail.top", "gamebcs.com", "garbagecollector.org", "garbagemail.org",
    "garliclife.com", "gawab.com", "gehensiemirnichtaufdensack.de",
    "gelitik.in", "get-mail.cf", "get-mail.ga", "get-mail.ml", "get-mail.tk",
    "get1mail.com", "get2mail.fr", "getairmail.cf", "getairmail.com",
    "getairmail.ga", "getairmail.gq", "getairmail.ml", "getairmail.tk",
    "geteit.com", "getnada.cc", "getnada.com", "getonemail.com",
    "getonemail.net", "getsimpleemail.com", "giantmail.de", "gimpmail.com",
    "ginzi.be", "ginzi.co.uk", "ginzi.es", "ginzi.net", "ginzy.co.uk",
    "ginzy.eu", "girlmail.win", "gishpuppy.com", "givmail.com",
    "glubex.com", "gmial.com", "gmial.com", "gmx1mail.top", "gmxmail.top",
    "gmxmail.win", "go2usa.info", "goatmail.uk", "goemailgo.com",
    "gomail.in", "gorillaswithdirtyarmpits.com", "gotmail.com",
    "gotmail.net", "gotmail.org", "grandmamail.com", "grandmasmail.com",
    "great-host.in", "greensloth.com", "grr.la", "gs-arc.org", "gsrv.co.uk",
    "guerillamail.biz", "guerillamail.com", "guerillamail.de",
    "guerillamail.info", "guerillamail.net", "guerillamail.org",
    "guerillamailblock.com", "guerrillamail.biz", "guerrillamail.com",
    "guerrillamail.de", "guerrillamail.info", "guerrillamail.net",
    "guerrillamail.org", "guerrillamailblock.com", "gustr.com",
    "guysmail.com", "h8s.org", "haben-wir.com", "habenwir.com",
    "haltospam.com", "hamham.uk", "harakirimail.com", "hat-geld.de",
    "hatespam.org", "haydoo.com", "hazmatshipping.org", "headstrong.de",
    "heathenhammer.com", "heathenhero.com", "hecat.es", "heheee.com",
    "hellodream.mobi", "herp.in", "herpderp.nl", "hezll.com",
    "hidemail.de", "hidemail.pro", "hidemail.us", "hidzz.com",
    "hmamail.com", "hoanggiaanh.com", "hoanglong.tech", "hola.org",
    "hopemail.biz", "hornyalwary.top", "hostcalls.com", "hostlaba.com",
    "hot-mail.cf", "hot-mail.ga", "hot-mail.gq", "hot-mail.ml", "hot-mail.tk",
    "hotmai.com", "hotmailproduct.com", "hotmial.com", "hotpop.com",
    "housat.com", "hpc.tw", "hs.vc", "ht.cx", "huangniu8.com",
    "hukkmu.tk", "hulapla.de", "humaility.com", "hushmail.cf",
    "hvastudiesucces.nl", "iaoss.com", "ibnuh.bz", "icantbelieveineedtoexplainthisshit.com",
    "icemail.club", "ich-essen-fleisch.bio", "icx.in", "icx.ro",
    "ieatspam.eu", "ieatspam.info", "ieh-mail.de", "iencm.com",
    "iffymedia.com", "ige.es", "ignoremail.com", "ihateyoualot.info",
    "ihazspam.ca", "iheartspam.org", "ikbenspamvrij.nl", "illistnoise.com",
    "ilovespam.com", "imails.info", "imgof.com", "imgv.de",
    "imstations.com", "inbax.tk", "inbox.si", "inbox2.info",
    "inboxalias.com", "inboxbear.com", "inboxclean.com", "inboxclean.org",
    "inboxed.im", "inboxed.pw", "inboxkitten.com", "inboxstore.me",
    "inclusiveprogress.com", "incognitomail.com", "incognitomail.net",
    "incognitomail.org", "incq.com", "ind.st", "indirect.ws",
    "indomaed.pw", "indomina.cf", "infocom.zp.ua", "inggo.org",
    "inoutmail.de", "inoutmail.eu", "inoutmail.info", "inoutmail.net",
    "insorg-mail.info", "instaddr.ch", "instaddr.uk", "instaddr.win",
    "instance-email.com", "instant-mail.de", "instantblingmail.info",
    "instantemailaddress.com", "instantletter.net", "instantmail.fr",
    "instmail.uk", "intopwa.com", "intopwa.net", "intopwa.org",
    "investore.co", "iozak.com", "ip6.li", "ip6.pp.ua", "ipoo.org",
    "iridales.com", "irish2me.com", "iroid.com", "ironiebehindert.de",
    "is.af", "isdaq.com", "ishop2k.com", "isosq.com", "ist-hier.de",
    "it2-mail.com", "it7.ovh", "iuc.edu.vn", "iwi.net", "ixx.io",
    "j-p.us", "jafps.com", "jamit.com.au", "jdmadventures.com",
    "jellyrolls.com", "jet-renovation.fr", "jetable.com", "jetable.fr.nf",
    "jetable.org", "jetable.pp.ua", "jnxjn.com", "job.craigslist.org",
    "jourrapide.com", "jp.ftp.sh", "jsrsolutions.com", "jumonji.tk",
    "jungkamushukum.com", "junk.to", "junk1e.com", "junkmail.ga",
    "junkmail.gq", "junkmail.ml", "junkmail.tk", "junkmail.win",
    "just-email.com", "justemail.ml", "justonemail.com", "jv6hgh1.com",
    "k3663a40w.com", "kaffeeschluerfer.com", "kaffeeschluerfer.de",
    "kakadua.net", "kalapi.org", "kamen-market.ru", "kamsg.com",
    "kariplan.com", "kasmail.com", "kaspop.com", "katztube.com",
    "kcrw.de", "keepmymail.com", "keinpardon.de", "kekita.com",
    "kellychibale-researchgroup.com", "kemptvillebaseball.com",
    "kennedy808.com", "kiani.com", "killmail.com", "killmail.net",
    "kimsdisk.com", "kingsq.ga", "kingsq.gq", "kingsq.ml", "kiois.com",
    "kismail.ru", "kisstwink.com", "kitnastar.com", "kitten-mittens.com",
    "klassmaster.com", "klassmaster.net", "klick-tipp.us", "klipp.su",
    "klipschx12.com", "kloap.com", "kludgemush.com", "klzlk.com",
    "kmail.moo.jp", "kook.ml", "kopagas.com", "kopaka.net", "kormail.xyz",
    "kostenlosemailadresse.de", "koszmail.pl", "kpooa.com", "kpost.be",
    "krd.ag", "krsw.tk", "ks87.igg.biz", "ks87.usa.cc", "kuh.mu",
    "kulturbetrieb.info", "kumail8.info", "kurzepost.de", "kvhrr.com",
    "kvhrs.com", "kvhrw.com", "kwift.net", "kwilco.net", "kyal.pl",
    "l-c-a.us", "l33r.eu", "labetteravergageld.de", "lackmail.net",
    "lackmail.ru", "ladybeat.com", "lakelivingstonrealestate.com",
    "lakmail.com", "landmail.co", "laoeq.com", "larjem.com", "last-chance.pro",
    "lastmail.co", "lastmail.com", "lawlita.com", "lawl.net", "lazyinbox.com",
    "lazyinbox.org", "ldaho.net", "ldop.com", "ldtp.com", "le-tim.ru",
    "lee.mx", "leeching.net", "legalrc.loan", "legendsclub.net",
    "lell.no", "lenovog4.com", "lerbhe.com", "lesbugs.com",
    "letmeinon.com", "letthemeatspam.com", "levy.ml", "lexisense.com",
    "lgxscreen.com", "lhsdv.com", "liamcyrus.com", "lifebyfood.com",
    "lifetimefriends.info", "lifetotech.com", "ligsb.com", "likno.com",
    "lillemap.net", "lilo.me", "lindenbaumjapan.com", "link2mail.net",
    "linkedintuts2016.pw", "linuxmail.so", "litedrop.com", "loadby.us",
    "loan101.pro", "loanins.org", "localserv.no", "locanto1.club",
    "locantofuck.top", "locantowsite.club", "locantowsite.top",
    "locateme10.com", "locomodev.net", "login-email.cf", "login-email.ga",
    "login-email.ml", "login-email.tk", "loh.pp.ua", "loin.in",
    "lol.ovpn.to", "lolfreak.net", "lolmail.biz", "lookugly.com",
    "lopl.co.cc", "lordsofts.com", "lortemail.dk", "losemymail.com",
    "lovemeet.faith", "lovemeet.review", "lovemeet.study", "lovemeet.website",
    "lpfmgmtltd.com", "lr78.com", "lroid.com", "lukop.dk", "luv2.us",
    "lyfestylecreditsolutions.com", "lyricspad.net", "m21.cc",
    "m4ilweb.info", "maboard.com", "macromaid.com", "macromice.info",
    "magamem.com", "magicbox.ro", "magspam.net", "maidlow.info",
    "mail-easy.com", "mail-fake.com", "mail-finder.com", "mail-hierarchie.de",
    "mail-hierarchie.eu", "mail-hierarchie.info", "mail-hierarchie.net",
    "mail-hierarchie.org", "mail-jetable.fr", "mail-jetable.net",
    "mail-jetable.org", "mail-jetable.xyz", "mail-owl.com", "mail-owl.net",
    "mail-owl.org", "mail-temp.com", "mail-temporaire.com",
    "mail-temporaire.fr", "mail-tester.com", "mail.by", "mail.mezimages.net",
    "mail114.net", "mail2rss.org", "mail333.com", "mail4trash.com",
    "mail666.ru", "mail707.com", "mail72.com", "mailadadad.org",
    "mailback.com", "mailbidon.com", "mailblocks.com", "mailbox72.biz",
    "mailbox80.biz", "mailbox92.biz", "mailbucket.org", "mailcat.biz",
    "mailcatch.com", "mailchop.com", "mailcker.com", "mailde.de",
    "mailde.info", "mailde.org", "maildrop.cc", "maildrop.cf",
    "maildrop.ga", "maildrop.gq", "maildrop.ml", "maildu.de",
    "maildx.com", "maileater.com", "maileimer.de", "maileme101.com",
    "mailexpire.com", "mailfa.tk", "mailfall.com", "mailforspam.com",
    "mailfree.ga", "mailfree.gq", "mailfree.ml", "mailfreeonline.com",
    "mailfs.com", "mailguard.me", "mailhazard.com", "mailhazard.us",
    "mailhz.me", "mailimate.com", "mailin8r.com", "mailinater.com",
    "mailinator.com", "mailinator.net", "mailinator.org", "mailinator.us",
    "mailinator2.com", "mailincubator.com", "mailismagic.com",
    "mailjunk.cf", "mailjunk.ga", "mailjunk.gq", "mailjunk.ml",
    "mailjunk.tk", "mailmate.com", "mailme.gq", "mailme.ir", "mailme.lv",
    "mailme24.com", "mailmetrash.com", "mailmoat.com", "mailmoth.com",
    "mailms.com", "mailna.biz", "mailna.co", "mailna.in", "mailna.me",
    "mailnator.com", "mailnesia.com", "mailnull.com", "mailonaut.com",
    "mailorc.com", "mailorg.org", "mailpick.biz", "mailproxsy.com",
    "mailrock.biz", "mailsac.com", "mailscheap.us", "mailscrap.com",
    "mailseal.de", "mailsearch.net", "mailshiv.com", "mailsiphon.com",
    "mailslapping.com", "mailslite.com", "mailsucker.net", "mailt.net",
    "mailt.top", "mailtechx.com", "mailtemp.info", "mailtome.de",
    "mailtothis.com", "mailtraps.com", "mailtrash.net", "mailtrix.net",
    "mailtv.net", "mailtv.tv", "mailzilla.com", "mailzilla.org",
    "makemetheking.com", "malayalamdtp.com", "malinche.ml",
    "malove.site", "mamber.net", "manifestgenerator.com", "mansiondev.com",
    "manybrain.com", "mark-compressoren.de", "marketlink.info",
    "markmurfin.com", "martin.enscaled.com", "martyndavis.com",
    "mask03.ru", "maskmail.net", "masonline.info", "mastodon.xyz",
    "maswae.world", "matamuasu.ga", "matamuasu.ml", "matchpol.net",
    "matra.site", "max-direct.com", "max88.club", "maximalbonus.de",
    "maxprice.co", "mbx.cc", "mcache.net", "mciek.com", "mdhc.tk",
    "mebelnu.info", "mechanicalresumes.com", "medkabinet-uz.ru",
    "meepsheep.eu", "mega.zik.dj", "meinspamschutz.de", "meltmail.com",
    "meltmail.net", "mems.top", "merry.pink", "messagebeamer.de",
    "messwiththebestdielikethe.rest", "metroset.net", "mettamark.ga",
    "mettamark.gq", "mettamark.ml", "mexcool.com", "mezimages.net",
    "mfsa.ru", "mfsa.store", "mhzayt.online", "miaferrari.com",
    "miauj.com", "midcoastcustoms.com", "midcoastcustoms.net",
    "midcoastcustoms.org", "midlertidig.com", "midlertidig.net",
    "midlertidig.org", "mierdamail.com", "migmail.pl", "migmail.pro",
    "migumail.com", "mihep.com", "mijnhva.nl", "milavitsaromania.ro",
    "mildin.org.ua", "mindless.com", "minecraftrabbithole.com",
    "minex-coin.com", "minimail.gq", "minimail.org", "ministry-of-silly-walks.de",
    "minsmail.com", "mintemail.com", "mintemail.net", "mirai.re",
    "misterpinball.de", "mji.ro", "mjukgansen.nu", "mkpdp.com",
    "ml8.ca", "mm5.se", "mmail.igg.biz", "mmailinater.com", "mmailpro.com",
    "moakt.cc", "moakt.com", "moakt.ws", "mobi.web.id", "mobilevpn.top",
    "moburl.com", "mockmyid.co", "mockmyid.com", "moeri.org",
    "mofu.be", "mohmal.com", "mohmal.in", "mohmal.tech", "momentics.ru",
    "monachat.tk", "monadi.ml", "moncourrier.fr.nf", "monemail.fr.nf",
    "monmail.fr.nf", "monumentmail.com", "moza.pl", "mozy.eu",
    "mp-j.ga", "mp-j.igg.biz", "mp-j.usa.cc", "mp4.xyz", "mr24.co",
    "msg.mailpunk.com", "msgden.com", "msgfarm.com", "mspeciosa.com",
    "msrc.ml", "msxd.com", "mt2009.com", "mt2014.com", "mt2015.com",
    "mt2016.com", "mt2017.com", "mt2018.com", "mt2019.com", "mtmdev.com",
    "muathegame.com", "muchomail.com", "mucincanon.com", "muehlacker.tk",
    "muell.icu", "muell.monster", "muell.xyz", "muellemail.com",
    "muellmail.com", "mufux.com", "muggltzel.com", "muimail.com",
    "munoubengoshi.gq", "musiccode.me", "musician.org", "mutant.me",
    "muttwalker.net", "mvrht.com", "mvrht.net", "mwarner.org",
    "mx0.wwwnew.eu", "mx19.wwwnew.eu", "mxfuel.com", "mxp.dnshigh.de",
    "mxp.dns-cloud.net", "my-pomsies.ru", "my10minutemail.com",
    "mybitti.de", "mycleaninbox.net", "myemailboxy.com", "myemailocean.com",
    "myindohome.services", "myinterserver.ml", "mykickassideas.com",
    "mymail-in.net", "mymail90.com", "mymailoasis.com", "mymailto.cf",
    "mymailto.ga", "mymailto.ml", "mynetstore.de", "myopang.com",
    "mypartyclip.de", "myphantomemail.com", "mysamp.de", "myspaceinc.com",
    "myspaceinc.net", "myspacepimpedup.com", "myspamless.com",
    "mytemp.email", "mytempemail.com", "mytempmail.com", "mytrashmail.com",
    "mywarnernet.net", "mywrld.site", "mywrld.top", "myzx.com",
    "n1nja.org", "nabuma.com", "nada.email", "nada.ltd", "nagi.be",
    "nakedtruth.biz", "nanonym.ch", "napalm51.nut.cc", "napalm51.usa.cc",
    "nationalgardeningclub.com", "naturalious.com", "nawmin.info",
    "nbzmr.com", "nctui.com", "negated.com", "neko2.net", "nekochan.fr",
    "nekochan.net", "neomailbox.com", "nepwk.com", "nervmich.net",
    "nervt.nicht.durch", "net1mail.com", "net2mail.com", "net3mail.com",
    "netmail3.net", "netmails.com", "netmails.net", "netricity.nl",
    "netris.net", "netviewer-france.com", "netzidiot.de", "neverbox.com",
    "nevermail.de", "new-purse.com", "newbpotato.tk", "newdawnnm.xyz",
    "newfilm24.ru", "newmail.top", "newtmail.com", "next.ovh",
    "nextstopvalhalla.com", "nezdiro.org", "nezzart.com", "nfast.net",
    "nguyenusedcars.com", "nh3.ro", "nice-4u.com", "nicewoodenbaskets.com",
    "nicknassar.com", "nickrizos.com", "nigge.rs", "nike.coms.hk",
    "nincsmail.com", "nincsmail.hu", "niwl.net", "nko.kr", "nl.szucsati.net",
    "nmfrvry.cf", "nmfrvry.ga", "nmfrvry.gq", "nmfrvry.ml", "nmfrvry.tk",
    "nnot.net", "nobulk.com", "noclickemail.com", "nodezine.com",
    "nodnor.club", "nogmailspam.info", "noicd.com", "noifeelings.com",
    "nokiamail.com", "nolemail.ga", "nom.za", "nomail.cf", "nomail.ga",
    "nomail.gq", "nomail.ml", "nomail.nodns.xyz", "nomail.pw",
    "nomail2me.com", "nomail2me.net", "nomail2me.org", "nomailthankyou.com",
    "nomorespamemails.com", "nomail.xl.cx", "nomail2me.com",
    "nomail2me.net", "nomail2me.org", "nomailthankyou.com",
    "nomorespamemails.com", "noref.in", "norih.com", "nospam.ze.tc",
    "nospam4.us", "nospamfor.us", "nospammail.net", "nospamthanks.info",
    "nostockui.com", "not0k.com", "notif.me", "notmailinator.com",
    "notsharingmy.info", "notspam.net", "nowhere.org", "nowmymail.com",
    "nowmymail.net", "npgfif.com", "nthrl.com", "nthrw.com",
    "ntlhelp.net", "nubescontrol.com", "nullbox.info", "nurfuerspam.de",
    "nut.cc", "nutpa.net", "nuts2trade.com", "nwldx.com", "nwldx.net",
    "nwytg.com", "nwytg.net", "ny7.me", "nypato.com", "nyrmusic.com",
    "o2stk.org", "o7i.net", "oalsp.com", "obfusko.com", "objectmail.com",
    "obobbo.com", "obxpestcontrol.com", "odaymail.com", "odem.com",
    "odnorazovoe.ru", "oepia.com", "oerpub.org", "offshore-proxies.net",
    "ohaaa.de", "ohi.tw", "ohioticketpayments.xyz", "oing.cf", "okclprojects.com",
    "okrent.us", "okzk.com", "olimp-case.ru", "olypme.ru", "omail.pro",
    "omnievents.org", "one-time.email", "one2mail.info", "onebiginbox.com",
    "onecitymail.com", "onelegalplan.com", "onemail1.com", "oneoffemail.com",
    "onetimeemail.xyz", "onewaymail.com", "onlatedotcom.info",
    "online.ms", "onlineidea.info", "onqin.com", "ontyne.biz",
    "oolus.com", "oonies.ru", "oopi.org", "opayq.com", "opende.de",
    "opendns.ro", "opentrash.com", "opmmedia.ga", "opp24.com",
    "optimaweb.me", "opwebw.com", "oranek.com", "ordinaryamerican.net",
    "oreidresume.com", "orgmbx.cc", "oroki.de", "oshietechan.link",
    "otherinbox.com", "ourklips.com", "ourpreviewdomain.com",
    "outlawspam.com", "outlookpro.net", "ovpn.to", "owlpic.com",
    "owlymail.com", "ownsyou.de", "oxopoha.com", "oyu.kr", "ozyl.de",
    "p-banlis.ru", "p33.org", "p71ce1.com", "pa9e.com", "pachilly.com",
    "pagina.de", "paharpurmim.ga", "pakadebu.ga", "pancakemail.com",
    "papierkorb.me", "paplease.com", "para2019.ru", "parcel4.net",
    "pardus.ru", "parlimentpetroleum.com", "partybombe.de",
    "partynight.at", "passwordmail.com", "pastebitch.com", "patonce.com",
    "pavilionx2.com", "pay-mon.com", "payperex2.com", "payspun.com",
    "pc1520.com", "pcmylife.com", "pcusers.otherinbox.com",
    "pdold.com", "peb.kr", "pebot.com", "pechkin.ru", "pechkin.store",
    "pecinan.com", "pecinan.net", "pecinan.org", "pedimed-szczecin.pl",
    "pencalc.xyz", "penis.computer", "penisgoes.in", "pepbot.com",
    "peppe.usa.cc", "pepsi.coms.hk", "personal-email.ml", "personalenvelope.com",
    "peterdethier.com", "petertijj.com", "petl.life", "petrolgames.com",
    "petronas.ga", "petronas.gq", "petronas.ml", "pfui.ru", "pfui.store",
    "phone-elkey.ru", "photo-impact.eu", "photomark.net", "phpbb.uu.gl",
    "phuongpt9.tk", "pi.vu", "piaa.me", "pickuplanet.com", "pietershop.com",
    "pii.at", "pii.email", "pii.at", "piki.si", "pimpedupmyspace.com",
    "pinehill-seattle.org", "pingir.com", "pinoymail.com", "pipeline.ru",
    "pipeline.store", "piracha.net", "pisls.com", "pitaniezdorovie.ru",
    "pivo-bar.ru", "pjjkp.com", "placemail.online", "planet-travel.club",
    "pleasenoham.org", "plhk.ru", "plhk.store", "ploae.com", "plw.me",
    "po-jar.ru", "pochtar.men", "podam.pl", "poh.pp.ua", "pojok.ml",
    "pokemail.net", "pokiemobile.com", "polacy-dzieciom.pl",
    "polarking.com", "polishxusb.com", "poly-swarm.com", "polyfaust.com",
    "polymnestore.com", "pooae.com", "poofy.org", "pookmail.com",
    "poopie.club", "pop3.xyz", "popcornfarm7.com", "popcornfly.com",
    "popgx.com", "popmail.io", "popmailserv.org", "popso.cf", "popso.ga",
    "popso.gq", "popso.ml", "popso.tk", "porsh.net", "porta.loyaltyprograms.tk",
    "posdz.com", "postacin.com", "postfach2go.de", "postheo.de",
    "postheo.eu", "postheo.info", "postheo.net", "postheo.org",
    "postonline.me", "poutineyourface.com", "powered.name", "powlearn.com",
    "ppetw.com", "pqoia.com", "pratikshakothari.com", "prayersa3.com",
    "predatorrat.cf", "predatorrat.ga", "predatorrat.gq", "predatorrat.ml",
    "predatorrat.tk", "premium-mail.fr", "premiumperson.website",
    "primabananen.net", "privacy.net", "privatdemail.net", "privy-mail.com",
    "privy-mail.de", "privy-mail.fr", "privymail.de", "privymail.fr",
    "pro-tag.org", "procrackers.com", "profast.top", "projectcl.com",
    "projectxd.com", "proprietativalcea.ro", "propscore.com",
    "protestore.co", "providier.com", "provmail.net", "proxymail.eu",
    "proxymail.info", "proxyparking.net", "prs7.xyz", "prtnx.com",
    "prtz.eu", "psh.me", "psles.com", "psoxs.com", "psychedelicwarrior.xyz",
    "pterodactyl.work", "ptp1.xyz", "pubgeres.ru", "pubgeres.store",
    "publi.innovatium.es", "pubmail886.com", "puglieisi.com",
    "pulpmail.us", "pumpkin.de", "pumps-fashion.com", "punkass.com",
    "purple.flu.cc", "purple.igg.biz", "purple.nut.cc", "purple.usa.cc",
    "put2.net", "putthisinyourspamdatabase.com", "pwrby.com",
    "q314.net", "q5vm7pi9.com", "qacquirep.com", "qafatwallet.com",
    "qasti.com", "qbfree.in", "qc.to", "qibl.at", "qipmail.net",
    "qiq.us", "qisdo.com", "qisoa.com", "qoika.com", "qpalong.com",
    "qq.com", "qq.my", "qsl.ro", "qt1.dk", "quadrafit.com",
    "quick-mail.club", "quick-mail.info", "quick-mail.online",
    "quickemail.info", "quickinbox.com", "quickmail.best", "quickmail.in",
    "quickmail.nl", "quickmail.rocks", "quickmail.run", "quickmail.xyz",
    "quickreport.net", "quid4pro.com", "ququb.com", "qvy.me", "qwickmail.com",
    "r0.igg.biz", "r2c.dev", "r31s4go.com", "r4nd0m.de", "r4unx.com",
    "ra3.us", "rabin.ca", "rabiot.reisen", "racedriver.com",
    "radecoratingltd.com", "radiku.ye.vc", "radiodependence.com",
    "raetp9.com", "rainmail.biz", "rainwater.de", "rajeshcon.cf",
    "raketenmann.de", "rancidhome.net", "randomail.net", "randomail.io",
    "rao.kr", "raqid.com", "rarame.club", "rawhidefc.org", "rax.la",
    "raxtest.com", "razemail.com", "rbb.org", "rcasd.com", "rcpt.at",
    "rdklcrv.xyz", "re-gister.com", "re-gister.net", "re-gister.org",
    "reality-concept.club", "reallymymail.com", "realtyalerts.ca",
    "receiveee.com", "recode.me", "reconmail.com", "recursor.net",
    "recyclemail.dk", "redfeathercrow.com", "redmail.tech",
    "reftoken.net", "regbypass.com", "regspaces.tk", "rejectmail.com",
    "remail.cf", "remail.ga", "remail.gq", "remail.ml", "remail.tk",
    "remarkable.rocks", "remote.li", "reptilegenetics.com",
    "resgedvgfed.com", "resmail.com", "resolution4.com", "retkesbusz.nem",
    "revolvingdoorhoax.org", "rfc822.org", "rgphotos.net", "rhombushorizons.com",
    "rhyta.com", "richfinances.com", "riddermark.de", "rifkian.ga",
    "risingsuntouch.com", "riski.cf", "rklips.com", "rm2rf.com",
    "rmpkr.com", "rmqkr.com", "rnailinator.com", "ro.lt", "robertspcrepair.com",
    "robot2.club", "robotmail.xyz", "rollindo.agency", "ronnierage.net",
    "rootfest.net", "rosebearmuy.com", "rotaniliam.com", "rowe.engineer",
    "royal.net", "royaldoodles.org", "rppkn.com", "rtrtr.com",
    "rtskiya.xyz", "ru.ru", "ruffrey.com", "rumgel.com", "runi.ca",
    "runxx.com", "ruu.kr", "rvb3.com", "rx.dred.ru", "rx.thedarkwings.org",
    "s0ny.net", "s33db0x.com", "sabrestlouis.com", "sackboii.com",
    "safaat.com", "safersignup.de", "safersignup.eu", "safetymail.info",
    "safetypost.de", "saharanightstempe.com", "salmeow.tk", "salonyfryzjerskie.pl",
    "samsclass.info", "sandcars.net", "sandelf.de", "temp-mail.org",
    "tempmail.com", "tempmail.net", "tempmail.org", "throwaway.email",
    "throwawayemail.com", "throwawaymail.com", "tittbit.in",
    "tmailinator.com", "toiea.com", "toomail.biz", "topranklist.de",
    "tormail.org", "tradermail.info", "trash-amil.com", "trash-mail.at",
    "trash-mail.com", "trash-mail.de", "trash-mail.ga", "trash-mail.gq",
    "trash-mail.ml", "trash-mail.tk", "trash2009.com", "trash2010.com",
    "trash2011.com", "trashbox.eu", "trashdevil.com", "trashdevil.de",
    "trashdevil.net", "trashdevil.org", "trashemail.de", "trashmail.at",
    "trashmail.com", "trashmail.de", "trashmail.ga", "trashmail.gq",
    "trashmail.io", "trashmail.me", "trashmail.net", "trashmail.org",
    "trashmail.ws", "trashmailer.com", "trashymail.com", "trashymail.net",
    "trbvm.com", "trbvm.net", "trickmail.net", "trillianpro.com",
    "tryalert.com", "turual.com", "twinmail.de", "twkly.ml",
    "twoweirdtricks.com", "txrsb.com", "tyldd.com", "u6lvty2.com",
    "uber-mail.com", "ubismail.net", "ucup.in", "uemail99.com",
    "ufacturing.com", "uggsrock.com", "uguuchantele.com", "uhhu.ru",
    "uk.to", "umy.kr", "undo.it", "unicredit.it", "unids.com",
    "unimark.org", "unit7lahaina.com", "unmail.ru", "upliftnow.com",
    "uplipht.com", "uploadnolimit.com", "urfunktion.de", "uroid.com",
    "us.af", "us.to", "used-product.fr", "username.e4ward.com",
    "username.f4ward.com", "ushijima1129.tk", "utiket.us", "uwork4.us",
    "v8man.com", "vaasfc4.tk", "valemail.net", "valhalladev.com",
    "vanacken.com", "vankin.de", "vctel.com", "vda.ro", "vddaz.com",
    "veanlo.com", "vektik.com", "veloxmail.net", "venompen.com",
    "verdejo.com", "veryday.info", "veryrealemail.com", "vesa.pw",
    "vfemail.net", "vickaent.tk", "viditag.com", "viewcastmedia.com",
    "viewcastmedia.net", "viewcastmedia.org", "vikingsonly.com",
    "vinernet.com", "vip-mail.tk", "vip.163.com", "vip.188.com",
    "vip.qq.com", "viralplays.com", "vixletdev.com", "vkcode.ru",
    "vmani.com", "vmpanda.com", "vnedu.com", "voidbay.com",
    "voltaer.com", "vomoto.com", "vorga.org", "votiputox.org",
    "voxelcore.com", "vpn.st", "vpn33.top", "vps30.com", "vps911.com",
    "vradportal.com", "vremonte24-store.ru", "vrmtr.com", "vsimcard.com",
    "vssms.com", "vtxmail.us", "vubby.com", "vuiy.pw", "vzlom4ik.tk",
    "w3internet.co.uk", "w918bsq.com", "w9y9640c.com", "wakingupesther.com",
    "waluk.org", "wanko.be", "watch-harry-potter.com", "watchever.biz",
    "watchfree.org", "watchfull.net", "watchironman3onlinefreefullmovie.com",
    "wazabi.club", "wbdev.tech", "wbml.net", "web-ideal.fr", "web-contact.info",
    "web-emailbox.eu", "web-emailbox.xyz", "web-id.app", "web-mail.pp.ua",
    "web2mailco.com", "webcontact-france.fr", "webemail.me",
    "webm4il.info", "webmail24.top", "webtrip.ch", "webuser.in",
    "wee.my", "wefjo.gq", "wefjo.ml", "weg-werf-email.de", "weg-werf-email.info",
    "weg-werf-email.net", "wegwerf-email-addressen.de", "wegwerf-email-addressen.net",
    "wegwerf-email.de", "wegwerf-email.info", "wegwerf-email.net",
    "wegwerf-emails.de", "wegwerf-emails.net", "wegwerfadresse.de",
    "wegwerfadresse.net", "wegwerfemail.com", "wegwerfemail.de",
    "wegwerfemail.info", "wegwerfemail.net", "wegwerfemail.org",
    "wegwerfemailadresse.com", "wegwerfmail.de", "wegwerfmail.info",
    "wegwerfmail.net", "wegwerfmail.org", "welikecookies.com",
    "wemel.top", "wetrainbayarea.com", "wetrainbayarea.org",
    "wfgdfhj.tk", "whatiaas.com", "whatifanalytics.com", "whatpaas.com",
    "whatsaas.com", "whatsmails.com", "whtjddn.33mail.com", "whopy.com",
    "whtjddn.33mail.com", "whopy.com", "wibblesmith.com", "wibblesmith.net",
    "wibblesmith.org", "wickmail.net", "wiemei.com", "wilemail.com",
    "willhackforfood.biz", "willselfdestruct.com", "wimsg.com",
    "winnweb.net", "wins.com.br", "wishan.net", "wiz2.site",
    "wiz2.space", "wlist.ro", "wmail.cf", "wmail.club", "wmail.tk",
    "wolfsmail.tk", "wolfsmail.tk", "wolfsmail.tk", "wolfsmail.tk",
    "work4uber.com", "wovz.com", "writeme.com", "wronghead.com",
    "ws.gy", "wudet.men", "wuespdj.xyz", "wupics.com", "wuzup.net",
    "wuzupmail.net", "wwjmp.com", "wwwnew.eu", "wxnw.net", "wytuku.com",
    "x24.com", "xag.co", "xag.co", "xcompress.com", "xcpy.com",
    "xents.com", "xjoi.com", "xl.cx", "xmail.com", "xmail.net",
    "xmaily.com", "xoxy.net", "xperiae5.com", "xrho.com", "xwaretech.com",
    "xwaretech.info", "xwaretech.net", "xww.ro", "xyn.in", "xyze.de",
    "yaboo.com", "yadavnaresh.com.np", "yapped.net", "ycare.de",
    "ycn.ro", "ye.vc", "yedi.org", "yep.it", "yepmail.net",
    "yogamaven.com", "yogamaven.com", "yogamaven.com", "yogamaven.com",
    "yopmail.com", "yopmail.fr", "yopmail.gq", "yopmail.net",
    "yopmail.org", "yordanmail.cf", "yorum.net", "you-spam.com",
    "yougotgoated.com", "youmail.ga", "youmailr.com", "youmails.online",
    "youporn.flu.cc", "youporn.igg.biz", "youporn.nut.cc", "youporn.usa.cc",
    "yourdomain.com", "yourspamgoesto.space", "yourtube.ml",
    "ypmail.webarnak.fr.eu.org", "yroid.com", "yugasandwich.com",
    "yui.it", "yuoia.com", "yuurok.com", "yxzx.net", "yyhmail.com",
    "z0d.eu", "z1p.biz", "z86.ru", "z86.store", "zain.site", "zainmax.net",
    "zaktouni.fr", "zapzapzap.net", "zavio.nl", "zaym-zaym.ru",
    "zdenka.net", "ze.tc", "zebins.com", "zebins.eu", "zehnminuten.de",
    "zehnminutenmail.de", "zep-hyr.com", "zepp.dk", "zepromail.com",
    "zer0mail.eu", "zesta.cf", "zesta.ga", "zesta.gq", "zesta.ml",
    "zesta.tk", "zeta-telecom.com", "zexeet9i5l49ocke.ga", "zhaoyuanedu.cn",
    "zhcne.com", "zhewei.com", "zhorachu.com", "zik.dj", "zimbail.me",
    "zipo.ro", "zipo.ro", "zipo.ro", "zipo.ro", "zmail.ga", "zmail.gq",
    "zmail.ml", "zmail.ga", "zmail.gq", "zmail.ml", "zoaxe.com",
    "zoemail.com", "zoemail.net", "zoemail.org", "zoetropes.org",
    "zomg.info", "zoooh.com", "zoooh.com", "zoooh.com", "zoooh.com",
    "zooz.com", "zooz.com", "zooz.com", "zooz.com", "zoutlook.com",
    "zp.ua", "zslsz.com", "zumpul.com", "zv68.com", "zxcv.com",
    "zxcvbnm.com", "zxcvbnm.tk", "zxcxc.com", "zxczxc.tk", "zylpu.ru",
    "zymuying.com", "zzi.us", "zzz.com",
})


def _load_domains() -> frozenset[str]:
    """Return disposable domains, optionally merged with custom file."""
    domains = set(_DEFAULT_DOMAINS)
    custom = Path(__file__).parent.parent / "disposable_domains.txt"
    if custom.exists():
        for line in custom.read_text().splitlines():
            d = line.split("#")[0].strip().lower()
            if d:
                domains.add(d)
    return frozenset(domains)


_DOMAINS: frozenset[str] | None = None


def _get_domains() -> frozenset[str]:
    global _DOMAINS
    if _DOMAINS is None:
        _DOMAINS = _load_domains()
    return _DOMAINS


def is_disposable_email(email: str) -> bool:
    """Return True if email domain is a known disposable/temp-mail provider."""
    if "@" not in email:
        return False
    domain = email.split("@")[-1].strip().lower()
    return domain in _get_domains()